#### Pandas For Data Analysis
1) Pandas is a python package providing fast,flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive.
 2) It was created by Wes McKinney in 2008

 Applications : 
 1) Easy Handling
 2) Size Mutability : Columns can be inserted and deleted from DataFrame and higher dimensional obejcts
 3) Automatic align the data for you in computations
 4) Powerful,flexible group by functionality.
 5) Flexible reshaping and pivoting of data sets.

 Pandas Series is a one-dimesnional labeled array capable of holding data of any type(integer,string,float,python objects,etc)

 The axis labels are collectively called index. Pandas Series is nothing but a column in an excel sheet.

 The objects supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.

##### Creation of DataFrames in Pandas

In [2]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [5]:
import pandas as pd

data = {"Name": ["Ankit", "Bhagya", "Chaitanya"],
        "Age":[23, 22, 24],
        "City": ["Delhi", "Mumbai", "Bangalore"]
        }
df=pd.DataFrame(data)
df

        Name  Age       City
0      Ankit   23      Delhi
1     Bhagya   22     Mumbai
2  Chaitanya   24  Bangalore

In [6]:
data1 = pd.read_excel("expense3.xlsx")
print(data1)

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04         123              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

##### Exploring Data in Pandas

In [15]:
import pandas as pd

df = pd.read_excel("expense3.xlsx")
df.head(5)
df.tail(5)

         Date    Category Sub-Category   Amount Payment Mode
24 2023-01-27        Food          Chai      10          UPI
25 2023-01-28  Essentials     Bedsheets    1025         Cash
26 2023-01-29       Bills       Mobile     1650          UPI
27 2023-01-29     Grocery          Daal     150         Cash
28 2023-01-30       Bills      Cylinder    1074          UPI

In [ ]:
df.info()  # It displays the data types,columns,etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           29 non-null     datetime64[ns]
 1   Category       29 non-null     object
 2   Sub-Category   29 non-null     object
 3   Amount         29 non-null     int64
 4   Payment Mode   25 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.3+ KB

In [17]:
df.describe()

                                Date        Amount
count                             29     29.000000
mean   2023-01-17 19:02:04.137931008   1039.620690
min              2023-01-01 00:00:00     10.000000
25%              2023-01-10 00:00:00     70.000000
50%              2023-01-19 00:00:00    257.000000
75%              2023-01-26 00:00:00    890.000000
max              2023-01-30 00:00:00  16000.000000
std                              NaN   2927.684353